# These are supported funding model platforms

github: [Bhai4You]
patreon: BullAnonymous







lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: ['https://rzp.io/l/L2IvYDb7']
